language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "iojs"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/494158d4eec52996b76a
    on_success: change
    on_start: never
